FROM base as build

ADD . /rabbitmq-capabilities-exchange
WORKDIR /rabbitmq-capabilities-exchange

RUN make && \
    make dist

FROM rabbitmq:management

COPY --from=build \
    /rabbitmq-capabilities-exchange/plugins/rabbitmq_capabilities_exchange-* \
    ./plugins/rabbitmq_capabilities_exchange

RUN rabbitmq-plugins enable --offline \
    rabbitmq_capabilities_exchange

EXPOSE 15671 15672
