FROM base as build

ADD . /rabbitmq-requirements-exchange
WORKDIR /rabbitmq-requirements-exchange

RUN make && \
    make dist

FROM rabbitmq:management

COPY --from=build \
    /rabbitmq-requirements-exchange/plugins/rabbitmq_requirements_exchange-* \
    ./plugins/rabbitmq_requirements_exchange

RUN rabbitmq-plugins enable --offline \
    rabbitmq_requirements_exchange

EXPOSE 15671 15672
